### ISSUE TITLE
openfl.js dist file

### ISSUE THREAD

**Issue by goldenratio** [openfl/openfl-js#11]
Hi,

Can you please provide openfl.js file. I don't want to use docker or npm to make builds. This will make life easier for beginners.

```
<script src="openfl.js></script>
<script>
// my code
</script>
```

Edit: you can make use of `releases` https://github.com/openfl/openfl-js/releases for dist files.

**Comment by jgranick** [comment]
Sure! We'll work on that :smile:

**Comment by jgranick** [comment]
This is now done! Dist versions of OpenFL are being built, now, we'll just have to figure out distribution, if NPM is enough to download, or if we have to post somewhere different (such as Github), we'll have to figure that out.

The work is finished in the "openfl" repository, as we are merging "openfl-js" back into the main project :wink:
