### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by saumya** [openfl/openfl-js#2]
Trying to run the `helloWorld` sample and its saying

```
Module not found: Error: Can't resolve 'openfl/display/BitmapData'
Module not found: Error: Can't resolve 'openfl/geom/Rectangle'
```
Actually there are no sources inside `node_modules` only file there is `src/openfl/index.js`

**Comment by saumya** [comment]
> If you install from NPM, the sources will be built (though I think we'll move them to /lib?)

I do install it from NPM
```
npm install --save openfl
```
and testing a new project `npm init` and not from the samples.

**Comment by jgranick** [comment]
Thanks @saumya, `npm publish` was stripping out my generated files. Should be fixed now with the latest NPM release :wink:

**Comment by elsassph** [comment]
@jgranick @mastef now it works but the alias (`openfl/lib/openfl` into `openfl`) has caused me some confusion (I was trying a dummy require without your webpack config). A paragraph about it in the readme would help.

**Comment by jgranick** [comment]
@elsassph It would be great to know if there are other conventions that developers expect from NPM libraries, when you can require multiple modules. There is also support for `require ("openfl")`, returning an object that mirrors the ordinary paths (such as `var Rectangle = require ("openfl").geom.Rectangle;`)

I assume that long-term, the better way to go is separate module paths, because that allows you to reduce the amount of code imported, unless tree-shaking is simple enough that no one would practically need/want to do that.

Thanks for the feedback

**Comment by saumya** [comment]
I agree about the `imports` mentioned by @elsassph and fixed it as suggested by @jgranick . 

The final workable code looks as below and works.

```
//ES5
//var openfl = require("openfl")

//ES6
import openfl from "openfl" 

// Below code is same for both ES5/ES6

const BitmapData = openfl.display.BitmapData;
const Rectangle = openfl.geom.Rectangle;

var bitmapData = new BitmapData(200,200,true,0xFF24AFC4);
var rect = new Rectangle(50,50,100,100);

bitmapData.fillRect(rect, 0xFFCCCCCC);

document.body.appendChild(bitmapData.image.src);

console.log("Hello World");
```

So yes, as suggested by @elsassph 

> A paragraph about it in the readme would help.

**Comment by elsassph** [comment]
Yes definitely both options should be documented, but I agree that the split paths are recommended nowadays, and better to reduce code size.

**Comment by mastef** [comment]
A few more examples for building the samples are in #3 

Although after the changes from #1 the `es6 bunnymark` fails on 
```
ERROR in ./Main.js
Module parse failed: Unexpected token (84:20)
You may need an appropriate loader to handle this file type.
|
|
|     stage_onEnterFrame = (event) => {
|
|         for (var i = 0; i < this.bunnies.length; i++) {
 @ ./entry.js 2:0-26
```

And the `typescript DisplayingABitmap` sample errors out with `no test specified`.
All the other samples should build correctly.

**Comment by elsassph** [comment]
ES6 probably needs Babel loader.
