### ISSUE TITLE
ESM support broken?

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl-js#6]
In `package.json` the module entry point is set as: `"module": "lib-esm/openfl/index.js"`

But the `lib-esm` folder is not distributed in npm
(verifiable in https://www.jsdelivr.com/package/npm/openfl?tab=files&version=9.3.3)

**Comment by joshtynjala** [comment]
Thanks! I removed `module` for the next release. I'm not sure that we ever actually distributed lib-esm in any version (though maybe the plan was to distribute it eventually), so the `module` field was seemingly added incorrectly.
